### ISSUE TITLE
Maximum sample values is too low and messages are not helping

### ISSUE THREAD

**Issue by eLvErDe** [jasper-software/jasper#137]
Hello,

I ran into an issue while using OpenCV built against your library and it failed to load my JPEG 2000 files.
The only issue I could spot is "maximum number of samples exceeded" stderr message but had absolutely no idea from where it was coming.

So, my first advice is to add a prefix "[libjasper]" to the error messages and maybe a suffix explaining it can be rebuilt by specifying -DCMAKE_C_FLAGS="-DJAS_DEC_DEFAULT_MAX_SAMPLES=<larger_value"

For my own use I added * 1024 to the value, and it turns out it was now sufficient to load a 115Mb JPEG file. I think it's a better value as a default, because I don't think there's an easy way to override the maximum_sample value when using your lib through OpenCV Python module.

Thanks in advance,

Best regards, Adam.

**Comment by MaxKellermann** [comment]
This is a difficult problem, and no matter what you do, somebody will complain.
If you have no limit, this is an easy loophole for DoS with a crafted file - you can make any application using JasPer allocate arbitrary amounts of memory.
If your limit is too high, smaller programs will be vulnerable to this DoS.
If your limit is too low, JasPer will fail to read some files.
The problem is that some people's "too low" is larger than other people's "too high".
I'm not sure what to do, how to solve this and leave nobody complaining.

**Comment by mdadams** [comment]
I agree with Max here.  There is no one maximum value that will suit all users.  The best solution is to simply build the library with a larger default maximum or specify codec options that override the default.  I am marking this issue as closed, since there is no one default value that will satisfy all users.
