### ISSUE TITLE
Multiple  Assertion failed in  jpc_math.c and jpc_dec.c

### ISSUE THREAD

**Issue by wcventure** [jasper-software/jasper#190]
Hi there,

Multiple  Assertion failed were discovered in  jpc_math.c and jpc_dec.c.

```
jasper: /home/wencheng/Experiment/jasper/src/libjasper/jpc/jpc_dec.c:1883: void jpc_dequantize(jas_matrix_t *, jpc_fix_t): Assertion `absstepsize >= 0' failed.
Aborted

jasper: /home/wencheng/Experiment/jasper/src/libjasper/jpc/jpc_dec.c:1703: void calcstepsizes(uint_fast16_t, int, uint_fast16_t *): Assertion `!((expn + (numrlvls - 1) - (numrlvls - 1 - ((bandno > 0) ? ((bandno + 2) / 3) : (0)))) & (~0x1f))' failed.
Aborted

jasper: /home/wencheng/Experiment/jasper/src/libjasper/jpc/jpc_math.c:94: int jpc_floorlog2(int): Assertion `x > 0' failed.
Aborted
```

**Comment by wcventure** [comment]
[POC.zip](https://github.com/mdadams/jasper/files/2702650/POC.zip)

**Comment by MaxKellermann** [comment]
1. is CVE-2017-5499, see https://github.com/jasper-maint/jasper/issues/2 and https://github.com/mdadams/jasper/issues/63; fixed by https://github.com/jasper-maint/jasper/commit/8c4e99592e7da53a9de2934bc7781535d0e0595d in our fork https://github.com/jasper-maint/jasper/

2. is CVE-2016-9399 / CVE-2017-13751, see https://github.com/jasper-maint/jasper/issues/1 and https://github.com/mdadams/jasper/issues/83, fixed by https://github.com/jasper-maint/jasper/commit/84d00fb29a22e360c2ff91bdc2cd81c288826bfc

3. is CVE-2016-9398, see https://github.com/jasper-maint/jasper/issues/10 and https://github.com/mdadams/jasper/issues/71; fixed by https://github.com/jasper-maint/jasper/commit/c6f9fb6ec7fc97a5c4213f9077faf8622685d160 in our fork https://github.com/jasper-maint/jasper/

**Comment by jubalh** [comment]
All merged now.
