### ISSUE TITLE
 warning: the use of `tmpnam' is dangerous, better use `mkstemp'

### ISSUE THREAD

**Issue by bengt-ehn** [jasper-software/jasper#206]
Hello,

There is link warning when using jasper (built from Conan): 

/home/[user]/.conan/data/jasper/2.0.14/conan/stable/package/xx/lib/libjasper.a(jas_stream.c.o): In function `jas_stream_tmpfile':
jas_stream.c:(.text+0x8c7): warning: the use of `tmpnam' is dangerous, better use `mkstemp'

**Comment by daravi** [comment]
This is related to #138. Seems like that patch was only partial and did not add changes for actually using the more secure mkstemp() instead of tmpnam() when it's available.

A complete patch would need to include the changes needed to replace tmpnam with mkstemp while considering the bug referenced in #138 discovered by Ghostscript and also replace L_tmpnam.

If a project maintainer could commend on this issue it would be great.

**Comment by jubalh** [comment]
> If a project maintainer could commend on this issue it would be great.

Did you read https://github.com/mdadams/jasper/issues/208 ?

**Comment by daravi** [comment]
> Did you read #208 ?

I did so I'm not holding my breath for a resolution. But whatever the outcome of that discussion, for this issue to go forward a comment from a maintainer is needed.
