### ISSUE TITLE
Security vulnerability: the MIF decoder opens arbitrary files

### ISSUE THREAD

**Issue by MaxKellermann** [jasper-software/jasper#241]
This code line opens arbitrary files with a path specified in the MIF file itself:
https://github.com/jasper-software/jasper/blob/1fcd12dcbb4ce2841dcdc875df23f4e84d1c9ac1/src/libjasper/mif/mif_cod.c#L182
This is an extremely dangerous "feature" which can be abused by attackers.
Since the JasPer's MIF codec is enabled by default, and MIF files are auto-detected, it is easy for an attacker to feed malicious files into a victim's JasPer library.
@mdadams what is this MIF file format, anyway? I've never heard of it before. Other than JasPer's source code, I couldn't find any information on the internet. Does anybody use it?
I suggest removing this format completely, because it is the safest way to fix all vulnerabilities in this part of JasPer.

**Comment by mdadams** [comment]
Do not remove support for MIF as it is used for testing and image processing researchers, and possibly other things. JasPer allows the library user to control which codecs are activated.  We can make the default not to activate MIF, but still have it built into the library so that the user can enable it if they need it.

**Comment by mdadams** [comment]
I have added cmake options to allow the MIF codec to be excluded from the library or included but disabled, requiring a library user to opt in to its use.  By default, the MIF codec is included but **disabled**.  It is not recommended that anyone other than testers or image processing researchers (or other people with rather exotic images) who need to use the MIF format enable its use.  This addresses this security issue.

**Comment by jubalh** [comment]
Next time please reference the related issue in the commit message. Then people 3 years from now can easily make the connection.
For the record, this was done in commit: https://github.com/jasper-software/jasper/commit/425f776c31f9285c17bfb33221835716ba1e8ef0

**Comment by MaxKellermann** [comment]
The security vulnerability is just there, it is just disabled by default.
Distributions will enable it, for example Debian has a policy that all optional features should be enabled.
This is a lousy solution!

**Comment by mdadams** [comment]
@MaxKellermann I need the ability to build JasPer with the MIF codec enabled for testing, as some functionality in the library cannot be tested with other codecs.  I have changed the naming of some of the cmake options.  Now, the only way to enable the MIF codec is to enable an option called JAS_ENABLE_DANGEROUS_INTERNAL_TESTING_MODE, which is disabled by default and accompanied by multiple comments saying that this option is for internal use by the JasPer development team only and potentially poses significant security risks if enabled.  No reasonable library packager concerned with security should enable such an option. Please refer to commit e50e334.

@jubalh I added a "Fixes ..." message in the log message for e50e334 for reasons that you mentioned in your earlier comment.  I have to try to do a better job at remembering to link my commit log messages to issues.
Incidentally, I made a new release (2.0.20) since quite a few changes have been made since 2.0.19.
