### ISSUE TITLE
Why is Jasper init deprecated?

### ISSUE THREAD

**Issue by Jamaika1** [jasper-software/jasper#243]
decoders_dcraw.cpp: In member function 'void LibRaw::redcine_load_raw()':
decoders_dcraw.cpp:1746:12: warning: 'int jas_init()' is deprecated [-Wdeprecated-declarations]
1746 | jas_init();
| ^
In file included from ../../libjasper/jasper.h:73,
from ../defines.h:73,
from ../dcraw_defs.h:24,
from decoders_dcraw.cpp:19:
../../libjasper/jas_init.h:77:19: note: declared here
77 | JAS_DLLEXPORT int jas_init(void);
| ^~~~~~~~

**Comment by jubalh** [comment]
Because it's not needed anymore.
The part is initialized at compile time now: https://github.com/jasper-software/jasper/commit/7b9d1b10006bda29d6a80b7492ef2ea9e1f588fe

How about next time you check the code yourself? It's explained there.

**Comment by mdadams** [comment]
With all due respect this user has a valid point.  The library API allowed users to enable and disable codecs at run time.  This was a DELIBERATE design choice.  Someone appears to have deleted this functionality and broken API compatibility without asking me about this.  Sigh.  Hi, Max.

**Comment by MaxKellermann** [comment]
This whole initialization/formats thing was horrible. Every aspect of it was horrible.

The initialization API is undocumented. What gets initialized and when should anybody call it?
What's the point of `jas_cleanup()`? When is anybody supposed to call it and why?
And I'm not yet talking about this awful `atexit()` kludge, which doesn't appear to make sense.
This whole API puts a burden on the application, makes it fragile, for no reason.

There were a few brief comments for the "fmt" functions, but they were obscure and did not describe the semantics.
It is not documented how applications can enable or disable individual formats. So the feature you complain that I removed, I did not know it exists, due to lack of documentation.

Reading the code, an application can only do `jas_image_clearfmts()` and then call `jas_image_addfmt()` for each format it wants to use. There was no way to disable MIF, for example (which is extremely dangerous, see https://github.com/jasper-software/jasper/issues/241). The application can only clear the format list, or not call `jas_init()`, trusting that nobody else calls it, and then register all formats but MIF. Seriously?

And even if an application developer tries it that way - what does it pass to `jas_image_addfmt()`? This is a very cumbersome function, and it requires copying code from `jas_init()`. Each time a new format gets added in a new JasPer version, all applications need to be updated. And applications break if a JasPer build disables one format, because the distribution decides it is not used (e.g. MIF because it has a critical vulnerability).

The initialization API was very badly designed, because it was not thread-safe, not idempotent, and it was not clear who is responsible for calling it. What if an application uses JasPer and intializes it, and a meta library such as ImageMagick also uses and initializes it; who wins? What if both the application and several libraries call it at the same time?

What if libMagick wants all the formats, but the application wants only two? How can they agree on which set of formats to use? There is no safe way to do it.

Nothing of this made any sense. And I thought you just didn't know how to initialize everything at compile time, so I thought this was a good improvement.

Of course, you can revert 7b9d1b10006bda29d6a80b7492ef2ea9e1f588fe, but I don't support reverting it, because the whole thing was badly designed and utterly broken.

**Comment by Jamaika1** [comment]
Sorry for the confusion. I don't want to upset anyone. Does it mean deleting jas_init() in my case?

**Comment by mdadams** [comment]
@Jamaika1 There is no need for you to apologize.  Your question was a perfectly reasonable one to ask.
You should keep jas_init in your code.  It is not possible to remove jas_init from the JasPer library without removing some fundamental functionality in the library and breaking API compatibility.

**Comment by mdadams** [comment]
@MaxKellermann Your objection to backing out the change is duly noted.  As we have discussed at some length as a separate discussion, you cannot simply delete parts of the library API just because you don't like it (or for other similar reasons).  It is not an excuse to say that you didn't know about it due to lack of documentation because you could always have asked me.  The problem is that you don't.  I don't object to reworking the API in a future release, after giving library users reasonable warning that things will be changing.  I do, however, object to screwing over the library users by deleting API functionality without warning.  Also, we do need the ability in the library to enable/disable codecs built into JasPer at run-time as well as allow the library user to plug in their own codecsat run-time (as code external to the JasPer library itself).
Incidentally, I cannot revert 7b9d1b1 without conflicts.  To avoid conflicts, I need to also revert c20f20b9.  I can revert both changes, or if you would prefer, I can let you revert 7b9d1b1 and modify appropriately.  It is up to you.  If I don't hear anything, I will assume that the first of these options is acceptable to you.

**Comment by MaxKellermann** [comment]
@mdadams, I'm glad you're back to managing JasPer after letting it rot for 4 years. After fixing all security vulnerabilities which have accumulated over those years (except for #241 where you don't like my proposed fix), my work is done. I have many ideas to improve JasPer, but after our recent disagreements, I feel my time is better spent on other projects. So the decision what to do here is only yours.

On:
> you could always have asked me

I did. You didn't reply, as always.

**Comment by osamu620** [comment]
@MaxKellermann I think you are one of the key contributors of JasPer. I wish I could dissuade you from leaving this project.

**Comment by mdadams** [comment]
@MaxKellermann You never asked me about any of the functions in the library API that you marked deprecated or removed entirely.  In any case, thank you for your recent work on JasPer.  It is appreciated, notwithstanding our disagreements.

**Comment by mdadams** [comment]
@Jamaika1 I have reverted the change that deprecated jas_init, as the other changes that allowed this function to be deprecated would have caused API breakage for library users (and ABI would have been broken due to removal of numerous functions in the API).  If you have any remaining concerns, please let me know.

**Comment by MaxKellermann** [comment]
@osamu620 too late, mdadams has (secretly) revoked my access to this project. Working with you (for this brief time) was a pleasure, thanks, and farewell.

**Comment by mdadams** [comment]
> @mdadams, I have many ideas to improve JasPer, but after our recent disagreements, I feel my time is better spent on other projects.

@MaxKellermann Since you said that your work was done on JasPer and you did not plan to continue to do work on it, I disabled write access to the repository (although I did not yet remove you as a repository contributor). This is not an unreasonable thing to do.  Only the current maintainers should have write access.  Giving write access to users who do not need it only poses a security risk in the event that their account is compromised.  If I misunderstood that you are not resigning as a maintainer, please clarify this, as it certainly seemed to me that you are were saying that you were stepping down due to our recent disagreements about library API changes.
