### ISSUE TITLE
ECCN for libjasper 

### ISSUE THREAD

**Issue by Likhitha2809** [jasper-software/jasper#251]
Hi, For documentation purpose and project release process we need the Export control classification number(ECCN) for libjasper if it applies. Can you please let me know the ECCN ?

**Comment by jubalh** [comment]
What??

**Comment by mdadams** [comment]
> Hi, For documentation purpose and project release process we need the Export control classification number(ECCN) for libjasper if it applies. Can you please let me know the ECCN ?

I presume that you are referring to the ECCNs used in the USA.  I do not live in the USA.  I am in Canada.  I believe that the other current JasPer maintainer Michael Vetter lives in Germany.  This being the case, it is not reasonable to expect us to know US export law and such.  My very limited understanding of ECCNs is that they are assigned by the organizations that are exporting items from the USA. You should consult with an appropriate expert in export law to determine how JasPer should be classified if you are choosing to export it from the USA.

Since, unless I have misunderstood, this issue is one of export law, it is not one that the JasPer development team can address.  Therefore, I am closing this issue.
