### ISSUE TITLE
oss-fuzz 31955 graphicsmagick:coder_JP2_fuzzer: Undefined-shift in jpc_undo_roi

### ISSUE THREAD

**Issue by bobfriesenhahn** [jasper-software/jasper#280]
oss-fuzz 31955 is determined to be a JasPer issue.  The full issue content is included in the attached tarball.  Please fix!

[oss-fuzz-31955.tar.gz](https://github.com/jasper-software/jasper/files/6135061/oss-fuzz-31955.tar.gz)

**Comment by mdadams** [comment]
When I use UBSan, I see three shifts that result in overflow.  For performance reasons, however, we allow overflow to happen in the computation of decoded sample data since this type of overflow it is harmless in practice.  In these three cases it is benign.  It will just lead to bad distortion in the decoded image.
