### ISSUE TITLE
oss-fuzz 32158 - graphicsmagick:coder_JPC_fuzzer: Timeout in coder_JPC_fuzzer (i386)

### ISSUE THREAD

**Issue by bobfriesenhahn** [jasper-software/jasper#285]
This is a hang in jpc_dec_tileinit(), which does seem likely to be specific to 32-bit builds.

[oss-fuzz-32158.tar.gz](https://github.com/jasper-software/jasper/files/6166582/oss-fuzz-32158.tar.gz)

**Comment by mdadams** [comment]
@bobfriesenhahn I'm running recent releases of Fedora on all of my machines and Fedora dropped 32 bit support quite a while ago.  So, I don't have any environment at present that I can use to debug this problem.  Can you provide more specifics about how things are failing?  Also, do you care about 32 bit from the point of view of your users?

**Comment by mdadams** [comment]
@bobfriesenhahn Although slow, this test case decodes for me without ASAN/UBSAN warnings on 64-bit x86.

**Comment by bobfriesenhahn** [comment]
On Fri, 19 Mar 2021, Michael Adams wrote:

> @bobfriesenhahn I'm running recent releases of Fedora on all of my 
> machines and Fedora dropped 32 bit support quite a while ago.  So, I 
> don't have any environment at present that I can use to debug this 
> problem.  Can you provide more specifics about how things are 
> failing?  Also, do you care about 32 bit from the point of view of 
> your users?

It is not usually too difficult to find/create a 32-bit build 
environment.  For example, VirtualBox can be used to install a 32-bit 
OS for test purposes.

MSYS2 still supports a 32-bit version under Microsoft Windows.  It 
does deliver a modern JasPer library.  This is another easy way to 
test under 32-bits if you have Windows available.

Of course I care about 32-bits since 32-bits is still important in the 
world due to being so common for so long.  Some hardware only supports 
32-bits.  If Debian still cares about 32-bit targets, then I 
definitely do too.

I will be going on a trip for the next couple of weeks.  I might still 
be able to look at this while on the trip.

Bob
-- 
Bob Friesenhahn
***@***.***, http://www.simplesystems.org/users/bfriesen/
GraphicsMagick Maintainer,    http://www.GraphicsMagick.org/
Public Key,     http://www.simplesystems.org/users/bfriesen/public-key.txt

**Comment by mdadams** [comment]
@bobfriesenhahn I spent quite a bit of time looking at this issue. I cannot find any evidence that this is a bug.  Putting the matter of 32 bit aside for the moment, I am suspicious of whether there is, in fact, anything wrong here.  You said that your test case does not fail but rather simply appears to hang.  Are you absolutely certain that the code is not simply taking more time than your test framework expects?  The JPC decoder does work correctly in my development environment for your test case.  That is, the decoder does not generate any ASAN/UBSAN errors/warnings and it correctly concludes that the codestream is invalid.  But the codestream is very slow to decode due to the coding parameters used.  When debugging and ASAN+UBSAN are enabled, the decoding of the coded file takes about 1 minute on my machine. The bizarre coding parameters used cause a lot of work to be done before the conclusion that the codestream is invalid.  Even without debugging enabled, decoding takes about 12 seconds.  Decoding does not result in excessive (i.e., dangerously high levels of) memory use.  It is mainly just very slow.  Again, this is not unexpected given the bizarre coding parameters in the codestream.  Unless you can confirm that the code is actually hanging (i.e., stuck with no forward progress) as opposed to just taking unusually long, I am reluctant to devote more time than I already have on this issue (which would appear not to be a bug).

To help with investigating this issue, I added some extra debugging log messages to the JPC/JP2 decoder in the tile initialization part of the code, which is what takes so long for the test case that you provided.  It would be helpful to run imginfo with the --debug-level option set so that you can see what is happening in the decoder when you are claiming that the code is hung.  This extra code is in commit 9cec977a2b492d4c56c876adb81de46c2ef4c397.

**Comment by bobfriesenhahn** [comment]
On Sat, 20 Mar 2021, Michael Adams wrote:

> @bobfriesenhahn I spent quite a bit of time looking at this issue. I 
> cannot find any evidence that this is a bug.  Putting the matter of 
> 32 bit aside for the moment, I am suspicious of whether there is, in 
> fact, anything wrong here.  You said that your test case does not 
> fail but rather simply appears to hang.  Are you absolutely certain 
> that the code is not simply taking more time than your test 
> framework expects?  The JPC decoder does work correctly in my

I expect that it is taking longer than the framework expects.  Fuzzing 
test cases which take a long time are the bane of fuzzing since they 
take all available resources.

There is a similar problem that if "slow" files are opened that they 
can take a long time to decode and appear to "hang" a user app, or 
clog a server which is otherwise used to handle thousands or millions 
of files from untrusted or semi-trusted users.  If such files are 
intentionally uploaded, it can be harmful to the server.  Ordinary 
JPEG has similar issues in that it is possible to produce a file which 
takes exceedingly long to decode.

Bob
-- 
Bob Friesenhahn
***@***.***, http://www.simplesystems.org/users/bfriesen/
GraphicsMagick Maintainer,    http://www.GraphicsMagick.org/
Public Key,     http://www.simplesystems.org/users/bfriesen/public-key.txt

**Comment by mdadams** [comment]
@bobfriesenhahn The problem is that JasPer cannot possibly know what is an "acceptable" level of CPU usage for decoding a coded bitstream.  Different applications will have vastly different definitions of "acceptable".  I ran into the same problem when trying to impose memory limits.  Ultimately, the application has to decide such things.  I do not see any way to fix this that would not result in some applications not being able to decode legitimate code streams with an amount of computation deemed "acceptable" to those applications.

**Comment by bobfriesenhahn** [comment]
On Fri, 26 Mar 2021, Michael Adams wrote:

> @bobfriesenhahn The problem is that JasPer cannot possibly know what is an "acceptable" level of CPU usage for decoding a coded bitstream.  Different applications will have vastly different definitions of "acceptable".  I ran into the same problem when trying to impose memory limits.  Ultimately, the application has to decide such things.  I do not see any way to fix this that would not result in some applications not being able to decode legitimate code streams with an amount of computation deemed "acceptable" to those applications.

A "progress" call-back function can be useful in order to allow the 
application to know how much work has been done, and to allow 
cancelling the operation.  Unfortunately, it can be difficult to know 
how much work there is to do, and it is difficult to insert a progress 
callback without slowing down critical loops.

Libjpeg does provide a call-back indication, which has now become the 
only way (other than an OS-dependent mechanism) for apps to defend 
against files which might take a year to decode.

Bob
-- 
Bob Friesenhahn
***@***.***, http://www.simplesystems.org/users/bfriesen/
GraphicsMagick Maintainer,    http://www.GraphicsMagick.org/
Public Key,     http://www.simplesystems.org/users/bfriesen/public-key.txt

**Comment by mdadams** [comment]
@bobfriesenhahn The JPEG2000 codec is orders of magnitude more complex than the original JPEG codec. Adding a proper callback mechanism would require a complete rewrite of JasPer from the ground up, and a complete change of the library API.  This is just not doable, practically speaking.  One can at least limit the execution time by limiting the number of samples in the image being decoded.  This is better than nothing, and it prevents the most obscene types of abuse.

**Comment by mdadams** [comment]
Since I have yet to receive clear evidence that there is a bug here (i.e., all evidence so far would seem to suggest that the code on master is simply slow but works correctly), I am going to close this issue.  If new information comes to light that demonstrates that there is, in fact, a bug lurking somewhere in the code, we can reopen this issue.
