### ISSUE TITLE
jas_stream_close closes a file object it didn't open

### ISSUE THREAD

**Issue by giraffedata** [jasper-software/jasper#286]
When I open a stream from an existing open file with jas_stream_fdopen(), then when I close that stream with jas_stream_close(), it should leave that file open.

In older libjasper, there was code in jas_stream_fdopen() to set the flag JAS_STREAM_NOCLOSE and code in jas_stream_close() to forego closing if that flag was set.

Current libjasper sets flag JAS_STREAM_FILEOBJ_NOCLOSE, but jas_stream_close() pays no attention to it and in practice, the file gets closed.  I see no place that JAS_STREAM_FILEOBJ_NOCLOSE .

**Comment by mdadams** [comment]
@giraffedata Just out of curiosity, in which version of JasPer did this previously work?  It seems to have been broken for a while.  In any case, I have added a check for this flag to the code.  Please confirm that it now works for you.  The fix is in commit 66f3d9d59e6eb4d7263c5e8511f25e2ace0e43be.

**Comment by giraffedata** [comment]
The version in which I see it work is 1.600.0.

I'll pass this along to the person who reported the problem to me.

-- 
Bryan Henderson                                   San Jose, California

**Comment by mdadams** [comment]
@giraffedata Thanks for the clarification.  The 1.600.0 version is very old.  In any case, the problem should be fixed now, I think.
