### ISSUE TITLE
Make test fails for i686 and armv7hl on Fedora

### ISSUE THREAD

**Issue by jridky** [jasper-software/jasper#287]
With the latest version of jasper (2.0.27) I am not able to build this package in Fedora Rawhide (35).
It fails for i686 and armv7hl arch during test phase with following error:

```
1: ############################################################
1: Input file: /builddir/build/BUILD/jasper-version-2.0.27/test/bin/../../data/test/bad/277.jp2
1: warning: not enough tile data (3 bytes)
1: imginfo: /builddir/build/BUILD/jasper-version-2.0.27/src/libjasper/jpc/jpc_dec.c:1950: jpc_dequantize: Assertion `absstepsize >= 0' failed.
1: /builddir/build/BUILD/jasper-version-2.0.27/test/bin/run_test_1: line 107: 3069179 Aborted                 (core dumped) ASAN_OPTIONS="${special_asan_options[*]}" "$imginfo" "${imginfo_opts[@]}" < "$in_file"
1: actual exit status: 134
1: expected exit status: 1
1: ERROR: imginfo command had unexpected exit status  (expected 1 got 134)
1: ############################################################
```
It looks like  commit 63a87fb0a1d5461d9cb5858b1edefa987155f283 introduced sth wrong.

**Comment by mdadams** [comment]
@jridky This commit did not change any code.  It just added a new test case, which has apparently detected a bug that you have encountered.  I suspect that this is a 32-bit issue, since this test case works fine on x86_64 but not i686.  Unfortunately, I don't have a 32-bit setup that I can use for debugging.  Maybe I can install an old 32-bit Fedora release in a VM and use that?  Am I correct that Fedora dropped 32-bit support in Fedora 31?  If so, I guess this just means that 32-bit ISO images are no longer built but 32-bit versions of libraries are still included in 64-bit builds, since you're working on Fedora 35/rawhide.  Is this correct?

**Comment by jridky** [comment]
Generally speaking, you're right. We no longer provide 32-bit versions of Fedora, but ARM versions are still "in game". I applied simple workaround during build for affected architectures only and removed this test case from their build folder. 

For test build environment, you may try https://copr.fedorainfracloud.org/, where you're able to build the package for all basic architectures available in Fedora  (+ 32-bit versions).

**Comment by mdadams** [comment]
@jridky Isn't this just a package building platform?  I ask because I need a full 32-bit development environment in order to debug.

**Comment by mdadams** [comment]
@jridky Since recent versions of Fedora do not support 32-bit x86, I built a 32-bit Ubuntu VM and did some testing/debugging with it.  The assertion in the JPC decoder that is failing should not be there.  When the assertion is false, a badly distorted image would likely be output by the decoder due to overflow, but this overflow is harmless.  The behavior of terminating in this case is inconsistent with other behavior in JasPer which is to always allow a decoded output to be generated when overflow occurs in the processing of sample data, since some decoded output (which may be distorted) is better than no output at all (due to aborting execution).  So, I have removed this assertion. The test case now passes on 32-bit Ubuntu, at least, and I would presume on the 32-bit cases you were testing.  Let me know if this does not fix the problem that you were experiencing.
