### ISSUE TITLE
shift exponent exceed in jpc_dec.c:2120:40

### ISSUE THREAD

**Issue by kdsjZh** [jasper-software/jasper#311]
A shift exponent error reported by UBSan.

Reproduce environment:
OS : ubuntu 18.04
Compiler : clang 12.0.0
Sanitizer option: `-fsanitize=integer,bounds,shift`
driver and args : jasper -f /path/to/seed -T pnm
version: commit 836a79c39cc467e9a45981c1dc9caf114bdb1e20 (newest one)
reproduce seed : [seed.zip](https://github.com/jasper-software/jasper/files/7728552/seed.zip)

**Comment by kdsjZh** [comment]
some of the error output
```
/benchmark/jasper-ubsan/test/jasper/src/libjasper/jpc/jpc_dec.c:2120:40: runtime error: shift exponent 4294967295 is too large for 64-bit type 'uint_fast32_t' (aka 'unsigned long')
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /benchmark/savior/jasper-ubsan/test/jasper/src/libjasper/jpc/jpc_dec.c:2120:40 in
```

**Comment by uvic-frodo** [comment]
This is not a bug in the sense that this behavior reflects design intent.  Overflow is deliberately allowed in the calculation of image sample values during decoding, since this poses no security risk and will only result in degraded decoded image quality.  If overflow were flagged as an error, no decoded image could be produced at all, which is IMHO overkill.
