### ISSUE TITLE
Jasper could not pass the conformance testing defined in ISO/IEC 15444-4

### ISSUE THREAD

**Issue by osamu620** [jasper-software/jasper#330]
With the 7a77a00ce0a6e9388e6dcd041eaea7030cb084cd, Jasper could not pass the conformance testing defined in ISO/IEC 15444-4. The detailed results of the test are shown as follows. 
The problems are found with p0_05.j2k and p1_03.j2k. For the first one, MSE values for components 1 and 2 are over the allowable threshold. For the second one,   PAE (Peak Absolute Error) for component 2 and MSE values for components 1 and 2 are over the threshold.

ISO/IEC JTC 1/SC 29/WG 1 (a.k.a. JPEG) found that the allowable error bounds for those components were too tight for 16-bit fixed-point implementation (please see a column "Proposed relaxed MSE bound"), however, the numbers in the following table are too large. The JPEG committee will have a meeting from July 25 - 29 and the issue will be discussed. Quick reactions from @mdadams are more than welcome.

||allowable error||Jasper (7a77a00ce0a6e9388e6dcd041eaea7030cb084cd)||Status||||||||||
|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
|TCS|Peak|MSE|Peak|MSE|Peak|MSE|Proposed relaxed MSE bound||||||||
|p0_01_0|0|0|0|0|Pass|Pass|||||||||
|p0_02_0|0|0|0|0|Pass|Pass|||||||||
|p0_03_0|0|0|0|0|Pass|Pass|||||||||
|p0_04_0|5|0.776|2|0.328551|Pass|Pass|||||||||
|p0_04_1|4|0.626|2|0.340999|Pass|Pass|||||||||
|p0_04_2|6|1.07|2|0.282155|Pass|Pass|||||||||
|p0_05_0|2|0.302|1|0.223977|Pass|Pass|0.319||||||||
|p0_05_1|2|0.307|2|0.455366|Pass|Fail|0.323||||||||
|p0_05_2|2|0.269|2|0.572094|Pass|Fail|0.317||||||||
|p0_05_3|0|0|0|0|Pass|Pass|||||||||
|p0_06_0|635|11287|367|2525.219548|Pass|Pass|||||||||
|p0_06_1|403|6124|25|24.54336|Pass|Pass|||||||||
|p0_06_2|378|3968|186|44.107932|Pass|Pass|||||||||
|p0_06_3|0|0|0|0|Pass|Pass|||||||||
|p0_07_0|0|0|0|0|Pass|Pass|||||||||
|p0_07_1|0|0|0|0|Pass|Pass|||||||||
|p0_07_2|0|0|0|0|Pass|Pass|||||||||
|p0_08_0|0|0|N/A *|N/A|Fail|Fail|*|Could not test p0_08 because JasPer does not support resolution reduction|||||||
|p0_08_1|0|0|N/A|N/A|Fail|Fail|||||||||
|p0_08_2|0|0|N/A|N/A|Fail|Fail|||||||||
|p0_09_0|0|0|0|0|Pass|Pass|||||||||
|p0_10_0|0|0|0|0|Pass|Pass|||||||||
|p0_10_1|0|0|0|0|Pass|Pass|||||||||
|p0_10_2|0|0|0|0|Pass|Pass|||||||||
|p0_11_0|0|0|0|0|Pass|Pass|||||||||
|p0_12_0|0|0|0|0|Pass|Pass|||||||||
|p0_14_0|0|0|0|0|Pass|Pass|||||||||
|p0_14_1|0|0|0|0|Pass|Pass|||||||||
|p0_14_2|0|0|0|0|Pass|Pass|||||||||
|p0_15_0|0|0|0|0|Pass|Pass|||||||||
|p1_01_0|0|0|0|0|Pass|Pass|||||||||
|p1_02_0|5|0.765|2|0.337236|Pass|Pass|||||||||
|p1_02_1|4|0.616|2|0.348307|Pass|Pass|||||||||
|p1_02_2|6|1.051|2|0.288418|Pass|Pass|||||||||
|p1_03_0|2|0.3|1|0.216512|Pass|Pass|0.311||||||||
|p1_03_1|2|0.21|2|0.417898|Pass|Fail|0.280||||||||
|p1_03_2|1|0.2|2|0.498768|Fail|Fail|0.267||||||||
|p1_03_3|0|0|0|0|Pass|Pass|||||||||
|p1_04_0|624|3080|253|58.06745|Pass|Pass|||||||||
|p1_05_0|40|8.458|11|0.439419|Pass|Pass|||||||||
|p1_05_1|40|9.716|7|0.452477|Pass|Pass|||||||||
|p1_05_2|40|10.154|16|0.416771|Pass|Pass|||||||||
|p1_06_0|2|0.6|1|0.076389|Pass|Pass|||||||||
|p1_06_1|2|0.6|1|0.027778|Pass|Pass|||||||||
|p1_06_2|2|0.6|1|0.083333|Pass|Pass|||||||||
|p1_07_0|0|0|0|0|Pass|Pass|||||||||
|p1_07_1|0|0|0|0|Pass|Pass|||||||||

**Comment by osamu620** [comment]
@mdadams 

Thank you for your quick response. I have sent you an email. Could you kindly check your mailbox?

**Comment by mdadams** [comment]
@osamu620  I have created a new script for running the JPEG-2000 conformance tests for JasPer in an automated manner.  The script is called run_conformance_tests (under the test/bin directory).  This script has also been integrated into the GitHub CI workflow for JasPer so that the conformance tests are run on each new commit.  The script is still a work in progress.  In particular (in the case of tests for Class 0), either there is an error in my script or some reference images in the conformance test suite seem incorrect (e.g., have the wrong number of components or resolution).  This is still under investigation.  I will let you know what I find.

**Comment by mdadams** [comment]
@osamu620: I am sorry but I just realized that I forgot to post a follow up comment for this issue.  I have added a CMake build option called JAS_ENABLE_CONFORMANCE_TESTS.  This option is a boolean flag and the default for this option is false.  If you set it to true, however, does this fix the conformance problems that you have identified in your comments above?  (This option, when set to true, increases the word size for fixed point arithmetric.)  This appears to fix things for me.  The only issue is that JasPer does not support decoding reduced resolution versions of images.  So, I have excluded the tests that require this functionality from the ones I have considered.  (I think that there were three such tests, but I am going from memory here so I might have the number wrong.)  Aside from these, I think that JasPer should be conforming.  I do not currently have time to add reduced resolution decoding support to JasPer.  If the tests now pass for you, I would like to make a new release of JasPer with these fixes.

**Comment by osamu620** [comment]
@mdadams 
Thank you for including the conformance mode. I have confirmed that JasPer now passes all the conformance tests defined 15444-4 except for the one that needs resolution reduction. 

Just curious about how much bits increase with JAS_ENABLE_CONFORMACE_TESTS?

**Comment by mdadams** [comment]
@osamu620 Since I do not currently have the resources/time to carefully go through the JPEG 2000 codec and determine where the radix point should be fixed at various points in the compression pipeline in order to minimize word size, I had to opt for the very inelegant solution of simply using 64 bits with the radix point fixed at the same bit position everywhere.  I think that JasPer had been using a 64-bit word size for JPEG 2000 on 64-bit machines by default anyways.  It has an option to use 32 bits, however, for improved speed.  If I have more time in the future, I can look into a more elegant solution.

**Comment by mdadams** [comment]
@osamu620 Incidentally, I still need to look at the other conformance test files that no one in the JPEG WG seems to care much about.  I think that these were the ones associated with Tables C.1 and C.4.  Some of these files seem wrong (or at least not sufficiently well documented to be useful) unless someone has updated them since July.

**Comment by mdadams** [comment]
@osamu620 I have now released JasPer 4.0.0, which includes the changes for conformance.

**Comment by mdadams** [comment]
@osamu620 The current setting for the number of fraction bits is determined in the code as follows:

#if defined(JAS_ENABLE_32BIT)
#define JPC_FIX_FRACBITS        13
#else
#define JPC_FIX_FRACBITS        18
#endif

So, the number of bits is either 13 or 18, depending on whether the fixed-point word size is 32 or 64.
Actually, the word size is determined by JAS_ENABLE_32BIT (which defaults to false, which means 64 bits on 64 bit architectures).  The JAS_ENABLE_CONFORMANCE_TESTS just enables the conformance tests when you run the JasPer test suite.
