### ISSUE TITLE
[Help document bug] For jasper, the help document misses some options

### ISSUE THREAD

**Issue by ccccmd** [jasper-software/jasper#344]
The "--help" option of jasper misses the option "cmptno", "memory-limit", "list-enabled-formats", "list-all-formats", "enable-format", "enable-all-formats"  for version 3.0.6.

+ For the option "cmptno", the following code appears during option parsing and modifies the cmdopts->cmptno in src/app/jasper.c:511-512 for version 3.0.6.

```
			cmdopts->cmptno = atoi(jas_optarg);
			break;
```

+ For the option "memory-limit", the following code appears during option parsing and modifies the cmdopts->max_mem in src/app/jasper.c:517-518 for version 3.0.6.

```
			cmdopts->max_mem = strtoull(jas_optarg, 0, 10);
			break;
```

+ For the option "list-enabled-formats", the following code appears during option parsing and modifies the cmdopts->list_codecs and cmdopts->list_codecs_all in src/app/jasper.c:480-482 for version 3.0.6.

```
			cmdopts->list_codecs = 1;
			cmdopts->list_codecs_all = 0;
			break;
```

+ For the option "list-all-formats", the following code appears during option parsing and modifies the cmdopts->list_codecs and cmdopts->list_codecs_all in src/app/jasper.c:484-486 for version 3.0.6.

```
			cmdopts->list_codecs = 1;
			cmdopts->list_codecs_all = 1;
			break;
```

+ For the option "enable-format", the following code appears during option parsing and modifies the cmdopts->enable_format in src/app/jasper.c:520-521 for version 3.0.6.

```
			cmdopts->enable_format = jas_optarg;
			break;
```

+ For the option "enable-all-formats", the following code appears during option parsing and modifies the cmdopts->enable_all_formats in src/app/jasper.c:523-524 for version 3.0.6.

```
			cmdopts->enable_all_formats = 1;
			break;
```

But they do not appear in the document provided by "--help".

It may prevent users from using the relevant function.

**Comment by mdadams** [comment]
This comment applies to #342, #343, #344, and #345.

Some changes to the usage information printed by various programs
and the manual have been made to address this issue.  Please read the
commit log message for more details.

IMPORTANT NOTES:

Some of the command-line options that were mentioned in this issue were
already documented in the manual but not in the usage information printed
by the program.  It was never the intention for the usage information
printed by the program to include information about every command-line
option.  Only some of the more common options were intended to be
identified.  A comment to this effect has been added to the usage message.

Please also note that some command-line options are very deliberately
undocumented (both in the manual and in the program usage information)
because they are intended only for internal use by the JasPer software
development team.  In some cases this is because the options pose
significant security risks if not used in a safe manner.  In other cases
this is because the options may be removed or changed without any notice.

**Comment by mdadams** [comment]
As an addendum to my previous comment:
The change can be found in commit e97639fe47faed62703ba47c1071b91e3d76eb41.
