### ISSUE TITLE
Undefined references error

### ISSUE THREAD

**Issue by coderodyhpc** [jasper-software/jasper#354]
Hello,
While compiling some apps(NCEPLIBS), I'm getting some errors:
```
/usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/9/../../../aarch64-linux-gnu/libg2_v3.1.0_4.a(enc_jpeg2000.c.o): in function `enc_jpeg2000_':
/home/ubuntu/POSTPRO/NCEPLIBS/download/nceplibs-g2/src/enc_jpeg2000.c:165: undefined reference to `jas_stream_memopen'
/usr/bin/ld: /home/ubuntu/POSTPRO/NCEPLIBS/download/nceplibs-g2/src/enc_jpeg2000.c:172: undefined reference to `jas_stream_memopen'
/usr/bin/ld: /home/ubuntu/POSTPRO/NCEPLIBS/download/nceplibs-g2/src/enc_jpeg2000.c:177: undefined reference to `jpc_encode'
/usr/bin/ld: /home/ubuntu/POSTPRO/NCEPLIBS/download/nceplibs-g2/src/enc_jpeg2000.c:186: undefined reference to `jas_stream_close'
/usr/bin/ld: /home/ubuntu/POSTPRO/NCEPLIBS/download/nceplibs-g2/src/enc_jpeg2000.c:187: undefined reference to `jas_stream_close'
/usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/9/../../../aarch64-linux-gnu/libg2_v3.1.0_4.a(enc_png.c.o): in function `user_write_data':

```
Libjasper is in a standard directory so I'm unsure which is the root of the problem. Could it be a matter of the app trying to use some phased out components?
Thanks

**Comment by mdadams** [comment]
As far as I can tell from the information that you posted, the problem is in the app using JasPer, not JasPer itself.  Please note that jpc_encode is an internal function.  It should not be called directly.  I believe that it is not exported when JasPer is build as a shared library.  I would suggest that you contact the maintainer of the app in question.
