### ISSUE TITLE
oss-fuzz issue 55515: graphicsmagick:coder_JPC_fuzzer: Timeout in coder_JPC_fuzzer

### ISSUE THREAD

**Issue by bobfriesenhahn** [jasper-software/jasper#377]
Please see https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=55515&sort=reported%20-id&q=graphicsmagick&can=6 for an GraphicsMagick oss-fuzz issue in JasPer which was first detected on Jan 29, 2023, and is now open for public consumption.

**Comment by mdadams** [comment]
When you get fuzzer timeouts like this, please check to confirm that the issue is, in fact, caused by a bug in JasPer.  You have often reported fuzzing timeouts, and I don't think that they have ever once corresponded to an actual bug in JasPer.  I was able to process this file with JasPer on the master branch, and it terminated after about 50 seconds on my notebook (with ASan and other instrumentation enabled, which likely slows down the code a bit).  In any case, there is no bug, since JasPer correctly handles the file.  In the absence of any reproducer for incorrect behavior, I am assuming that there is no problem here.

**Comment by bobfriesenhahn** [comment]
I report such issues because oss-fuzz only allows 30 seconds.

Bob

**Comment by mdadams** [comment]
My point is simply that, when a fuzzing test fails due to a timeout, you really ought to try running the test case manually yourself to confirm that a bug exists before filing a bug report against JasPer.  You have filed numerous bug reports due to timeouts to date, and I don't think that any of them actually corresponded to real bugs.  They were simply that the timeout was set too low.  In the future, it would be very much appreciated if you could check if timeout bugs are real bugs before filing a bug report against JasPer.

**Comment by bobfriesenhahn** [comment]
I did run the test case manually myself.  Why do you assume that I did not?

As I already mentioned, oss-fuzz imposes hard coded limits that I have 
no control over.  Reports such as this one are a service to you given 
otherwise you would be unaware that there appear to be bug reports 
against JasPer.

Bob
