### ISSUE TITLE
invalid memory read in jpc_undo_roi (jpc_dec.c)

### ISSUE THREAD

**Issue by asarubbo** [jasper-software/jasper#89]
On 1.900.27:

```
warning: trailing garbage in marker segment (56 bytes)
warning: trailing garbage in marker segment (41 bytes)
warning: trailing garbage in marker segment (44 bytes)
warning: trailing garbage in marker segment (69 bytes)
warning: trailing garbage in marker segment (69 bytes)
warning: trailing garbage in marker segment (78 bytes)
warning: trailing garbage in marker segment (36 bytes)
warning: trailing garbage in marker segment (69 bytes)
warning: trailing garbage in marker segment (42 bytes)
warning: not enough tile data (765 bytes)
warning: bad segmentation symbol
warning: bad segmentation symbol
warning: bad segmentation symbol
warning: forcing negative ROI shift to zero (bitstream is probably corrupt)
warning: forcing negative ROI shift to zero (bitstream is probably corrupt)
ASAN:DEADLYSIGNAL
=================================================================
==22872==ERROR: AddressSanitizer: SEGV on unknown address 0x7f8a4a950800 (pc 0x7f8e4a543b93 bp 0x7ffe29bfdcd0 sp 0x7ffe29bfdb80 T0)
==22872==The signal is caused by a READ memory access.
    #0 0x7f8e4a543b92 in jpc_undo_roi /tmp/portage/media-libs/jasper-1.900.27/work/jasper-1.900.27/src/libjasper/jpc/jpc_dec.c:1925:10
    #1 0x7f8e4a543b92 in jpc_dec_tiledecode /tmp/portage/media-libs/jasper-1.900.27/work/jasper-1.900.27/src/libjasper/jpc/jpc_dec.c:1104
    #2 0x7f8e4a534cdf in jpc_dec_process_sod /tmp/portage/media-libs/jasper-1.900.27/work/jasper-1.900.27/src/libjasper/jpc/jpc_dec.c:658:7
    #3 0x7f8e4a53e6b3 in jpc_dec_decode /tmp/portage/media-libs/jasper-1.900.27/work/jasper-1.900.27/src/libjasper/jpc/jpc_dec.c:425:10
    #4 0x7f8e4a53e6b3 in jpc_decode /tmp/portage/media-libs/jasper-1.900.27/work/jasper-1.900.27/src/libjasper/jpc/jpc_dec.c:262
    #5 0x7f8e4a4a0b84 in jas_image_decode /tmp/portage/media-libs/jasper-1.900.27/work/jasper-1.900.27/src/libjasper/base/jas_image.c:444:16
    #6 0x509eed in main /tmp/portage/media-libs/jasper-1.900.27/work/jasper-1.900.27/src/appl/imginfo.c:219:16
    #7 0x7f8e495a861f in __libc_start_main /var/tmp/portage/sys-libs/glibc-2.22-r4/work/glibc-2.22/csu/libc-start.c:289
    #8 0x419978 in _init (/usr/bin/imginfo+0x419978)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /tmp/portage/media-libs/jasper-1.900.27/work/jasper-1.900.27/src/libjasper/jpc/jpc_dec.c:1925:10 in jpc_undo_roi
==22872==ABORTING
```

Testcase: https://github.com/asarubbo/poc/blob/master/00054-jasper-invalidread-jpc_undo_roi

**Comment by adarshdinesh** [comment]
https://github.com/mdadams/jasper/blob/master/src/libjasper/jpc/jpc_dec.c#L1925. Here the base address of the matrix is passed to the function jpc_undo_roi() which can be controlled by corrupting the bit stream.

for ( i = 0; (signed __int64)i < *(_QWORD *)(a1 + 40); ++i )
{
  for ( j = 0; (signed __int64)j < *(_QWORD *)(a1 + 48); ++j )
  {
    v15 = *(_QWORD *)(8LL * j + *(_QWORD *)(8LL * i + *(_QWORD *)(a1 + 56))); // crashing here
    v12 = (v15 ^ (v15 >> 63)) - (v15 >> 63);
    if ( 1 << v8 > v12 )

**Comment by setharnold** [comment]
Agostino, did this get a CVE number yet?

Thanks

**Comment by thoger** [comment]
CVE-2017-5504
https://blogs.gentoo.org/ago/2017/01/16/jasper-invalid-memory-read-in-jpc_undo_roi-jpc_dec-c/

**Comment by thoger** [comment]
This is crashing because `x->rows_[]` in `jpc_undo_roi()` is an invalid pointer.

The matrix passed to `jpc_undo_roi()` is what's allocated / initialized in `jpc_dec_tileinit()` as `band->data`:

https://github.com/mdadams/jasper/blob/version-2.0.12/src/libjasper/jpc/jpc_dec.c#L835

The `jas_seq2d_bindsub()` is called with:

~~~
jas_seq2d_bindsub (s=0x610960, s1=0x610240, xstart=-8192, ystart=1058094, xend=-1, yend=1058095)

(gdb) p *s
$61 = {flags_ = 0, xstart_ = 0, ystart_ = 0, xend_ = 0, yend_ = 0, numrows_ = 0, numcols_ = 0, rows_ = 0x0, maxrows_ = 0, 
  data_ = 0x0, datasize_ = 0}

(gdb) p *s1
$62 = {flags_ = 0, xstart_ = 2147467264, ystart_ = 1058094, xend_ = 2147483647, yend_ = 1058095, numrows_ = 1, numcols_ = 16383, 
  rows_ = 0x606050, maxrows_ = 1, data_ = 0x7ffff7fd6010, datasize_ = 16383}
~~~

and subsequently `jas_matrix_bindsub()` called with:

~~~
jas_matrix_bindsub (mat0=0x610960, mat1=0x610240, r0=0, c0=-2147475456, r1=0, c1=-2147467266)
~~~

The `+ c0` part here causes `mat0->rows_[]` to contain invalid pointer:

https://github.com/mdadams/jasper/blob/version-2.0.12/src/libjasper/base/jas_seq.c#L254

Not yet sure what would be the right fix.

**Comment by ConzeHsu** [comment]
`$ jasper --input testcase --output tmp.bmp --output-format bmp
warning: trailing garbage in marker segment (14 bytes)
warning: trailing garbage in marker segment (145 bytes)
[1]    4563 abort      jasper --input  --output tmp.bmp --output-format bmp
`
I don't understand where the problem is
Testcase:
[testcase.zip](https://github.com/mdadams/jasper/files/4014754/testcase.zip)

**Comment by Ofirnir123** [comment]
Hi, Is this issue already fixed or won't be fixed soon? 
Thanks!

**Comment by jubalh** [comment]
It's not fixed.

**Comment by MaxKellermann** [comment]
Since this project has been mostly dead for several years, we created a fork which aims to fix all vulnerabilities (of which there are many).
This bug will be fixed by https://github.com/jasper-maint/jasper/pull/38 (merge pending)
